TQ.UI/Controllers/CategoryQuestionLinksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TQ.Data;

namespace TQ.UI.Controllers
{
    public class CategoryQuestionLinksController : Controller
    {
        private QuestionsEntities db = new QuestionsEntities();

        // GET: CategoryQuestionLinks
        [Authorize]
        public ActionResult Index()
        {
            var categoryQuestionLinks = db.CategoryQuestionLinks.Include(c => c.Category).Include(c => c.Question);
            return View(categoryQuestionLinks.ToList());
        }

        // GET: CategoryQuestionLinks/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoryQuestionLink categoryQuestionLink = db.CategoryQuestionLinks.Find(id);
            if (categoryQuestionLink == null)
            {
                return HttpNotFound();
            }
            return View(categoryQuestionLink);
        }

        // GET: CategoryQuestionLinks/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.CID = new SelectList(db.Categories, "CID", "Name");
            ViewBag.QID = new SelectList(db.Questions, "QID", "Question1");
            return View();
        }

        // POST: CategoryQuestionLinks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "QID,CID,LinkID")] CategoryQuestionLink categoryQuestionLink)
        {
            if (ModelState.IsValid)
            {
                db.CategoryQuestionLinks.Add(categoryQuestionLink);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CID = new SelectList(db.Categories, "CID", "Name", categoryQuestionLink.CID);
            ViewBag.QID = new SelectList(db.Questions, "QID", "Question1", categoryQuestionLink.QID);
            return View(categoryQuestionLink);
        }

        // GET: CategoryQuestionLinks/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoryQuestionLink categoryQuestionLink = db.CategoryQuestionLinks.Find(id);
            if (categoryQuestionLink == null)
            {
                return HttpNotFound();
            }
            ViewBag.CID = new SelectList(db.Categories, "CID", "Name", categoryQuestionLink.CID);
            ViewBag.QID = new SelectList(db.Questions, "QID", "Question1", categoryQuestionLink.QID);
            return View(categoryQuestionLink);
        }

        // POST: CategoryQuestionLinks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "QID,CID,LinkID")] CategoryQuestionLink categoryQuestionLink)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categoryQuestionLink).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CID = new SelectList(db.Categories, "CID", "Name", categoryQuestionLink.CID);
            ViewBag.QID = new SelectList(db.Questions, "QID", "Question1", categoryQuestionLink.QID);
            return View(categoryQuestionLink);
        }

        // GET: CategoryQuestionLinks/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoryQuestionLink categoryQuestionLink = db.CategoryQuestionLinks.Find(id);
            if (categoryQuestionLink == null)
            {
                return HttpNotFound();
            }
            return View(categoryQuestionLink);
        }

        // POST: CategoryQuestionLinks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            CategoryQuestionLink categoryQuestionLink = db.CategoryQuestionLinks.Find(id);
            db.CategoryQuestionLinks.Remove(categoryQuestionLink);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TQ.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Technical Interview Questions</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Site.css" rel="stylesheet" />

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Technical Interview Questions", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Random Question", "Random", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    
                    <li class="dropdown">
                        <a class="btn btn-secondary dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            More
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("All Questions", "List", "Home")</li>

                            @if (Request.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Manager")))
                            {
                                <li>@Html.ActionLink("Questions", "Index", "Questions")</li>
                                <li>@Html.ActionLink("Categories", "Index", "Categories")</li>
                                <li>@Html.ActionLink("Question Linker", "Index", "CategoryQuestionLinks")</li>
                                if (User.IsInRole("Admin"))
                                {
                                    <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                                    <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                                }
                            }
                        </ul>
                    </li>




                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>
    <footer id="footer" class="text-center">
        <p>&copy; @DateTime.Now.Year - Alysha & Jonathon</p>
    </footer>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>